name: social_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  circular_profile_avatar: ^2.0.5
  country_picker: ^2.0.12
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  event_bus: ^2.0.0
  faker: ^2.0.0
  file_picker: ^4.5.1
  fl_chart: ^0.46.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_image_compress: ^1.1.0
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  hive_flutter: ^1.1.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  overlay_support: ^1.2.1
  page_transition: ^2.0.5
  pin_code_fields: ^7.3.0
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  route_animation_helper: ^2.0.0+7
  shared_preferences: ^2.0.13
  persistent_bottom_nav_bar: ^4.0.2
  google_maps_flutter: ^2.1.2
  location: ^4.3.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1
  flutter_test:
    sdk: flutter
  json_model: ^1.0.0
  json_serializable: ^6.1.5

flutter_icons:
  android: "logo"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#ffffff"
  color_dark: "#ffffff"
  android: true
  ios: true
  # ios_content_mode: "scaleAspectFill"
  # android_gravity: "fill"

jsonToDart:
  outputFolder: lib/models #default: lib/
  typeChecking: true #default: undefined (Select from picker)
  nullValueDataType: String #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
